services:
  pmanagament:
    image: docker-registry.guarico.gob.ve/api_project_managament:latest
    restart: unless-stopped
    ports:
      - "7102:4200"
    depends_on:
      - pmanagament_db
    environment:
      - DATABASE_URL=postgresql://postgres:yepweyq@pmanagament_db:5432/api_project_managament
      - HOST_URL=https://api-gestiondeproyectos.guarico.gob.ve
    volumes:
      - pmanagament-static:/app/static
    networks:
      pmanagament-network:
        ipv4_address: "188.19.0.3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://188.19.0.3:4200/api/healthcheck"]
      interval: 5s
      timeout: 10s
      retries: 2
    links:
      - pmanagament_db
  pmanagament_db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yepweyq
      POSTGRES_DB: project_managament
    volumes:
      - pmanagament-db-data:/var/lib/postgresql/data
    ports:
      - "7103:5432"
    networks:
      pmanagament-network:
        ipv4_address: "188.19.0.2"

networks:
  pmanagament-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "188.19.0.0/16"
volumes:
  pmanagament-db-data:
    driver: local
  pmanagament-static:
    driver: local