UPDATE activity SET area = ('social') WHERE id = 8;
UPDATE activity SET area = ('economico') WHERE id = 9;
UPDATE activity SET area = ('seguridad') WHERE id = 11;
UPDATE activity SET area = ('social') WHERE id = 13;
UPDATE activity SET area = ('social') WHERE id = 14;
UPDATE activity SET area = ('social') WHERE id = 15;
UPDATE activity SET area = ('salud_educacion') WHERE id = 16;
UPDATE activity SET area = ('obras_servicios') WHERE id = 17;
UPDATE activity SET area = ('economico') WHERE id = 18;
UPDATE activity SET area = ('obras_servicios') WHERE id = 19;
UPDATE activity SET area = ('social') WHERE id = 21;
UPDATE activity SET area = ('salud_educacion') WHERE id = 22;
UPDATE activity SET area = ('social') WHERE id = 23;
UPDATE activity SET area = ('social') WHERE id = 25;
UPDATE activity SET area = ('social') WHERE id = 26;
UPDATE activity SET area = ('obras_servicios') WHERE id = 27;
UPDATE activity SET area = ('obras_servicios') WHERE id = 28;
UPDATE activity SET area = ('obras_servicios') WHERE id = 29;
UPDATE activity SET area = ('social'), ente = ('05-00') WHERE id = 31;
UPDATE activity SET area = ('obras_servicios') WHERE id = 32;
UPDATE activity SET area = ('economico') WHERE id = 33;
UPDATE activity SET area = ('social') WHERE id = 34;
UPDATE activity SET area = ('economico') WHERE id = 35;
UPDATE activity SET area = ('seguridad') WHERE id = 36;
UPDATE activity SET area = ('obras_servicios') WHERE id = 37;
UPDATE activity SET area = ('economico') WHERE id = 38;
UPDATE activity SET area = ('obras_servicios') WHERE id = 39;
UPDATE activity SET area = ('salud_educacion') WHERE id = 40;
UPDATE activity SET area = ('obras_servicios') WHERE id = 41;
UPDATE activity SET area = ('obras_servicios') WHERE id = 42;
UPDATE activity SET area = ('economico') WHERE id = 43;
UPDATE activity SET area = ('economico') WHERE id = 44;
UPDATE activity SET area = ('salud_educacion') WHERE id = 45;
UPDATE activity SET area = ('obras_servicios') WHERE id = 46;
UPDATE activity SET area = ('social') WHERE id = 47;
UPDATE activity SET area = ('social') WHERE id = 48;
UPDATE activity SET area = ('obras_servicios') WHERE id = 49;
UPDATE activity SET area = ('social') WHERE id = 50;
UPDATE activity SET area = ('obras_servicios') WHERE id = 51;
UPDATE activity SET area = ('economico') WHERE id = 52;
UPDATE activity SET area = ('salud_educacion') WHERE id = 53;
UPDATE activity SET area = ('salud_educacion') WHERE id = 54;
UPDATE activity SET area = ('social') WHERE id = 55;
UPDATE activity SET area = ('obras_servicios') WHERE id = 56;
UPDATE activity SET area = ('obras_servicios') WHERE id = 58;
UPDATE activity SET area = ('obras_servicios') WHERE id = 59;
UPDATE activity SET area = ('economico') WHERE id = 60;
UPDATE activity SET area = ('social') WHERE id = 61;
UPDATE activity SET area = ('obras_servicios') WHERE id = 62;
UPDATE activity SET area = ('salud_educacion') WHERE id = 63;
UPDATE activity SET area = ('obras_servicios') WHERE id = 65;
UPDATE activity SET area = ('social') WHERE id = 66;
UPDATE activity SET area = ('salud_educacion') WHERE id = 67;
UPDATE activity SET area = ('economico') WHERE id = 68;
UPDATE activity SET area = ('salud_educacion') WHERE id = 69;
UPDATE activity SET area = ('salud_educacion') WHERE id = 70;
UPDATE activity SET area = ('economico') WHERE id = 71;
UPDATE activity SET area = ('obras_servicios') WHERE id = 72;
UPDATE activity SET area = ('social') WHERE id = 73;
UPDATE activity SET area = ('obras_servicios') WHERE id = 74;
UPDATE activity SET area = ('social') WHERE id = 75;
UPDATE activity SET area = ('obras_servicios') WHERE id = 76;
UPDATE activity SET area = ('social') WHERE id = 77;
UPDATE activity SET area = ('economico') WHERE id = 78;
UPDATE activity SET area = ('obras_servicios') WHERE id = 79;
UPDATE activity SET area = ('economico') WHERE id = 80;
UPDATE activity SET area = ('salud_educacion') WHERE id = 81;
UPDATE activity SET area = ('salud_educacion') WHERE id = 82;
UPDATE activity SET area = ('salud_educacion') WHERE id = 83;
UPDATE activity SET area = ('salud_educacion') WHERE id = 84;
UPDATE activity SET area = ('obras_servicios') WHERE id = 85;
UPDATE activity SET area = ('salud_educacion') WHERE id = 86;
UPDATE activity SET area = ('obras_servicios') WHERE id = 87;
UPDATE activity SET area = ('obras_servicios') WHERE id = 88;
UPDATE activity SET area = ('salud_educacion') WHERE id = 89;
UPDATE activity SET area = ('economico') WHERE id = 91;
UPDATE activity SET area = ('economico') WHERE id = 92;
UPDATE activity SET area = ('economico') WHERE id = 93;
UPDATE activity SET area = ('social') WHERE id = 94;
UPDATE activity SET area = ('social') WHERE id = 95;
UPDATE activity SET area = ('obras_servicios') WHERE id = 96;
UPDATE activity SET area = ('obras_servicios') WHERE id = 97;
UPDATE activity SET area = ('economico') WHERE id = 98;
UPDATE activity SET area = ('salud_educacion') WHERE id = 99;
UPDATE activity SET area = ('social') WHERE id = 100;
UPDATE activity SET area = ('social') WHERE id = 101;
UPDATE activity SET area = ('salud_educacion') WHERE id = 102;
UPDATE activity SET area = ('economico') WHERE id = 103;
UPDATE activity SET area = ('economico') WHERE id = 104;
UPDATE activity SET area = ('obras_servicios') WHERE id = 105;
UPDATE activity SET area = ('seguridad') WHERE id = 106;
UPDATE activity SET area = ('salud_educacion') WHERE id = 107;
UPDATE activity SET area = ('salud_educacion') WHERE id = 108;
UPDATE activity SET area = ('salud_educacion') WHERE id = 109;
UPDATE activity SET area = ('salud_educacion') WHERE id = 110;
UPDATE activity SET area = ('obras_servicios') WHERE id = 111;
UPDATE activity SET area = ('seguridad') WHERE id = 112;
UPDATE activity SET area = ('obras_servicios') WHERE id = 113;
UPDATE activity SET area = ('obras_servicios') WHERE id = 114;
UPDATE activity SET area = ('seguridad') WHERE id = 115;
UPDATE activity SET area = ('seguridad') WHERE id = 116;
UPDATE activity SET area = ('obras_servicios') WHERE id = 117;
UPDATE activity SET area = ('social') WHERE id = 118;
UPDATE activity SET area = ('economico') WHERE id = 119;
UPDATE activity SET area = ('social') WHERE id = 120;
UPDATE activity SET area = ('salud_educacion') WHERE id = 121;
UPDATE activity SET area = ('economico') WHERE id = 122;
UPDATE activity SET area = ('salud_educacion') WHERE id = 123;
UPDATE activity SET area = ('social') WHERE id = 124;
UPDATE activity SET area = ('salud_educacion') WHERE id = 125;
UPDATE activity SET area = ('social') WHERE id = 126;
UPDATE activity SET area = ('social') WHERE id = 127;
UPDATE activity SET area = ('obras_servicios') WHERE id = 128;
UPDATE activity SET area = ('social') WHERE id = 129;
UPDATE activity SET area = ('economico') WHERE id = 130;
UPDATE activity SET area = ('economico') WHERE id = 131;
UPDATE activity SET area = ('obras_servicios') WHERE id = 132;
UPDATE activity SET area = ('obras_servicios') WHERE id = 133;
UPDATE activity SET area = ('obras_servicios') WHERE id = 134;
UPDATE activity SET area = ('obras_servicios') WHERE id = 135;
UPDATE activity SET area = ('social') WHERE id = 136;
UPDATE activity SET area = ('obras_servicios') WHERE id = 137;
UPDATE activity SET area = ('social') WHERE id = 138;
UPDATE activity SET area = ('obras_servicios') WHERE id = 139;
UPDATE activity SET area = ('seguridad') WHERE id = 141;
UPDATE activity SET area = ('obras_servicios') WHERE id = 142;
UPDATE activity SET area = ('obras_servicios') WHERE id = 143;
UPDATE activity SET area = ('seguridad') WHERE id = 144;
UPDATE activity SET area = ('salud_educacion') WHERE id = 145;
UPDATE activity SET area = ('social') WHERE id = 146;
UPDATE activity SET area = ('salud_educacion') WHERE id = 147;
UPDATE activity SET area = ('salud_educacion') WHERE id = 148;
UPDATE activity SET area = ('obras_servicios') WHERE id = 149;
UPDATE activity SET area = ('social') WHERE id = 150;
UPDATE activity SET area = ('obras_servicios') WHERE id = 151;
UPDATE activity SET area = ('obras_servicios') WHERE id = 152;
UPDATE activity SET area = ('obras_servicios') WHERE id = 153;
UPDATE activity SET area = ('social') WHERE id = 154;
UPDATE activity SET area = ('obras_servicios') WHERE id = 155;
UPDATE activity SET area = ('obras_servicios') WHERE id = 156;
UPDATE activity SET area = ('obras_servicios') WHERE id = 157;
UPDATE activity SET area = ('economico') WHERE id = 158;
UPDATE activity SET area = ('obras_servicios') WHERE id = 159;
UPDATE activity SET area = ('obras_servicios') WHERE id = 160;
UPDATE activity SET area = ('salud_educacion') WHERE id = 161;
UPDATE activity SET area = ('salud_educacion') WHERE id = 162;
UPDATE activity SET area = ('seguridad') WHERE id = 163;
UPDATE activity SET area = ('salud_educacion') WHERE id = 164;
UPDATE activity SET area = ('seguridad') WHERE id = 165;
UPDATE activity SET area = ('social') WHERE id = 166;
UPDATE activity SET area = ('social') WHERE id = 167;
UPDATE activity SET area = ('salud_educacion') WHERE id = 168;
UPDATE activity SET area = ('economico') WHERE id = 169;
UPDATE activity SET area = ('social') WHERE id = 170;
UPDATE activity SET area = ('social') WHERE id = 171;
UPDATE activity SET area = ('social') WHERE id = 172;
UPDATE activity SET area = ('salud_educacion') WHERE id = 173;
UPDATE activity SET area = ('salud_educacion') WHERE id = 175;
UPDATE activity SET area = ('social') WHERE id = 176;
UPDATE activity SET area = ('social') WHERE id = 177;
UPDATE activity SET area = ('obras_servicios') WHERE id = 178;
UPDATE activity SET area = ('social') WHERE id = 179;
UPDATE activity SET area = ('social') WHERE id = 180;
UPDATE activity SET area = ('economico') WHERE id = 181;
UPDATE activity SET area = ('social') WHERE id = 182;
UPDATE activity SET area = ('economico') WHERE id = 183;
UPDATE activity SET area = ('social') WHERE id = 184;
UPDATE activity SET area = ('social') WHERE id = 185;
UPDATE activity SET area = ('social') WHERE id = 186;
UPDATE activity SET area = ('social') WHERE id = 187;
UPDATE activity SET area = ('social') WHERE id = 188;
UPDATE activity SET area = ('obras_servicios') WHERE id = 189;
UPDATE activity SET area = ('social') WHERE id = 190;
UPDATE activity SET area = ('obras_servicios') WHERE id = 222;
UPDATE activity SET area = ('social') WHERE id = 223;
UPDATE activity SET area = ('obras_servicios') WHERE id = 224;
UPDATE activity SET area = ('social') WHERE id = 225;
UPDATE activity SET area = ('salud_educacion') WHERE id = 226;
UPDATE activity SET area = ('obras_servicios') WHERE id = 227;
UPDATE activity SET area = ('economico') WHERE id = 228;
UPDATE activity SET area = ('social') WHERE id = 229;
UPDATE activity SET area = ('social') WHERE id = 230;
UPDATE activity SET area = ('economico') WHERE id = 231;
UPDATE activity SET area = ('social') WHERE id = 232;
UPDATE activity SET area = ('seguridad') WHERE id = 233;
UPDATE activity SET area = ('economico') WHERE id = 234;
UPDATE activity SET area = ('economico') WHERE id = 235;
UPDATE activity SET area = ('obras_servicios') WHERE id = 236;
UPDATE activity SET area = ('social') WHERE id = 237;
UPDATE activity SET area = ('social') WHERE id = 238;
UPDATE activity SET area = ('social') WHERE id = 239;
UPDATE activity SET area = ('social') WHERE id = 240;
UPDATE activity SET area = ('economico') WHERE id = 241;
UPDATE activity SET area = ('economico') WHERE id = 242;
UPDATE activity SET area = ('social') WHERE id = 243;
UPDATE activity SET area = ('social') WHERE id = 244;
UPDATE activity SET area = ('social') WHERE id = 245;
UPDATE activity SET area = ('finanzas') WHERE id = 246;
UPDATE activity SET area = ('finanzas') WHERE id = 247;
UPDATE activity SET area = ('social') WHERE id = 249;
UPDATE activity SET area = ('social') WHERE id = 250;
UPDATE activity SET area = ('economico') WHERE id = 251;
UPDATE activity SET area = ('social') WHERE id = 252;
UPDATE activity SET area = ('social') WHERE id = 253;
UPDATE activity SET area = ('economico'), ente = ('21-00') WHERE id = 263;
UPDATE activity SET area = ('salud_educacion'), ente = ('09-00') WHERE id = 264;
UPDATE activity SET area = ('social'), ente = ('1008') WHERE id = 265;
UPDATE activity SET area = ('obras_servicios'), ente = ('1045') WHERE id = 266;
UPDATE activity SET area = ('obras_servicios'), ente = ('1036') WHERE id = 267;
UPDATE activity SET area = ('economico'), ente = ('21-00') WHERE id = 268;
UPDATE activity SET area = ('economico'), ente = ('21-00') WHERE id = 269;
UPDATE activity SET area = ('social'), ente = ('1003') WHERE id = 270;
UPDATE activity SET area = ('obras_servicios'), ente = ('16-00') WHERE id = 271;
UPDATE activity SET area = ('obras_servicios'), ente = ('1036') WHERE id = 272;
UPDATE activity SET area = ('social'), ente = ('1003') WHERE id = 273;
UPDATE activity SET area = ('obras_servicios'), ente = ('16-00') WHERE id = 274;
UPDATE activity SET area = ('social'), ente = ('1003') WHERE id = 275;
UPDATE activity SET area = ('economico'), ente = ('21-00') WHERE id = 276;
UPDATE activity SET area = ('economico'), ente = ('21-00') WHERE id = 277;
UPDATE activity SET area = ('salud_educacion'), ente = ('07-00') WHERE id = 278;
UPDATE activity SET area = ('salud_educacion'), ente = ('09-00') WHERE id = 279;
UPDATE activity SET area = ('obras_servicios'), ente = ('16-00') WHERE id = 280;
UPDATE activity SET area = ('salud_educacion'), ente = ('09-00') WHERE id = 281;
UPDATE activity SET area = ('salud_educacion'), ente = ('09-00') WHERE id = 282;
UPDATE activity SET area = ('salud_educacion'), ente = ('09-00') WHERE id = 283;
UPDATE activity SET area = ('obras_servicios'), ente = ('1045') WHERE id = 284;
UPDATE activity SET area = ('salud_educacion'), ente = ('09-00') WHERE id = 285;
UPDATE activity SET area = ('obras_servicios'), ente = ('1045') WHERE id = 286;
UPDATE activity SET area = ('salud_educacion'), ente = ('09-00') WHERE id = 287;
UPDATE activity SET area = ('social'), ente = ('1003') WHERE id = 288;
UPDATE activity SET area = ('social'), ente = ('1000') WHERE id = 289;
UPDATE activity SET area = ('economico'), ente = ('21-00') WHERE id = 290;
UPDATE activity SET area = ('social'), ente = ('1003') WHERE id = 291;
UPDATE activity SET area = ('social'), ente = ('1003') WHERE id = 292;
UPDATE activity SET area = ('obras_servicios'), ente = ('1039') WHERE id = 293;
UPDATE activity SET area = ('obras_servicios'), ente = ('1045') WHERE id = 294;
UPDATE activity SET area = ('social'), ente = ('05-00') WHERE id = 295;
UPDATE activity SET area = ('economico'), ente = ('21-00') WHERE id = 296;
UPDATE activity SET area = ('obras_servicios'), ente = ('1039') WHERE id = 297;
UPDATE activity SET area = ('obras_servicios'), ente = ('1039') WHERE id = 298;
UPDATE activity SET area = ('social'), ente = ('1010') WHERE id = 299;
UPDATE activity SET area = ('economico'), ente = ('21-00') WHERE id = 300;
UPDATE activity SET area = ('obras_servicios'), ente = ('1036') WHERE id = 301;
UPDATE activity SET area = ('economico'), ente = ('1004') WHERE id = 302;
UPDATE activity SET area = ('obras_servicios'), ente = ('20-00') WHERE id = 303;
UPDATE activity SET area = ('social'), ente = ('1010') WHERE id = 304;
UPDATE activity SET area = ('obras_servicios'), ente = ('1036') WHERE id = 305;
UPDATE activity SET area = ('economico'), ente = ('21-00') WHERE id = 306;
UPDATE activity SET area = ('economico'), ente = ('21-00') WHERE id = 307;
UPDATE activity SET area = ('obras_servicios'), ente = ('1036') WHERE id = 308;
UPDATE activity SET area = ('obras_servicios'), ente = ('16-00') WHERE id = 309;
UPDATE activity SET area = ('social'), ente = ('1010') WHERE id = 310;
UPDATE activity SET area = ('obras_servicios'), ente = ('1036') WHERE id = 311;
UPDATE activity SET area = ('social'), ente = ('1003') WHERE id = 312;
UPDATE activity SET area = ('social'), ente = ('05-00') WHERE id = 313;
UPDATE activity SET area = ('salud_educacion'), ente = ('07-00') WHERE id = 314;
UPDATE activity SET area = ('salud_educacion'), ente = ('07-00') WHERE id = 315;
UPDATE activity SET area = ('social'), ente = ('1010') WHERE id = 316;
UPDATE activity SET area = ('obras_servicios'), ente = ('1036') WHERE id = 317;
UPDATE activity SET area = ('social'), ente = ('1003') WHERE id = 318;
UPDATE activity SET area = ('obras_servicios'), ente = ('1039') WHERE id = 319;
UPDATE activity SET area = ('obras_servicios'), ente = ('1045') WHERE id = 320;
UPDATE activity SET area = ('social'), ente = ('1003') WHERE id = 321;
UPDATE activity SET area = ('obras_servicios'), ente = ('1036') WHERE id = 322;
UPDATE activity SET area = ('social'), ente = ('05-00') WHERE id = 323;
UPDATE activity SET area = ('obras_servicios'), ente = ('1045') WHERE id = 324;
UPDATE activity SET area = ('salud_educacion'), ente = ('08-00') WHERE id = 325;
UPDATE activity SET area = ('social'), ente = ('1000') WHERE id = 326;
UPDATE activity SET area = ('obras_servicios'), ente = ('20-00') WHERE id = 327;
UPDATE activity SET area = ('social'), ente = ('1003') WHERE id = 328;
UPDATE activity SET area = ('politico'), ente = ('00-00') WHERE id = 331;
UPDATE activity SET area = ('politico'), ente = ('00-00') WHERE id = 332;
UPDATE activity SET area = ('politico'), ente = ('00-00') WHERE id = 333;
UPDATE activity SET area = ('politico'), ente = ('00-00') WHERE id = 334;
UPDATE activity SET area = ('politico'), ente = ('00-00') WHERE id = 335;
UPDATE activity SET area = ('politico'), ente = ('00-00') WHERE id = 336;
UPDATE activity SET area = ('politico'), ente = ('00-00') WHERE id = 337;
UPDATE activity SET area = ('politico'), ente = ('00-00') WHERE id = 338;
UPDATE activity SET area = ('politico'), ente = ('00-00') WHERE id = 339;
UPDATE activity SET area = ('politico'), ente = ('00-00') WHERE id = 340;
UPDATE activity SET area = ('politico'), ente = ('00-00') WHERE id = 341;
UPDATE activity SET area = ('politico'), ente = ('00-00') WHERE id = 342;
UPDATE activity SET area = ('politico'), ente = ('00-00') WHERE id = 343;
UPDATE activity SET area = ('politico'), ente = ('00-00') WHERE id = 344;
UPDATE activity SET area = ('politico'), ente = ('00-00') WHERE id = 345;
UPDATE activity SET area = ('politico'), ente = ('00-00') WHERE id = 346;
UPDATE activity SET area = ('politico'), ente = ('00-00') WHERE id = 347;
UPDATE activity SET area = ('politico'), ente = ('00-00') WHERE id = 348;
UPDATE activity SET area = ('politico'), ente = ('00-00') WHERE id = 349;
UPDATE activity SET area = ('politico'), ente = ('00-00') WHERE id = 350;
UPDATE activity SET area = ('politico'), ente = ('00-00') WHERE id = 351;
UPDATE activity SET area = ('politico'), ente = ('00-00') WHERE id = 352;
UPDATE activity SET area = ('politico'), ente = ('00-00') WHERE id = 353;
UPDATE activity SET area = ('politico'), ente = ('00-00') WHERE id = 354;
UPDATE activity SET area = ('politico'), ente = ('00-00') WHERE id = 355;
UPDATE activity SET area = ('politico'), ente = ('00-00') WHERE id = 356;
UPDATE activity SET area = ('politico'), ente = ('00-00') WHERE id = 357;
UPDATE activity SET area = ('politico'), ente = ('00-00') WHERE id = 358;
UPDATE activity SET area = ('politico'), ente = ('00-00') WHERE id = 359;
UPDATE activity SET area = ('politico'), ente = ('00-00') WHERE id = 360;
UPDATE activity SET area = ('politico'), ente = ('00-00') WHERE id = 361;
UPDATE activity SET area = ('politico'), ente = ('00-00') WHERE id = 362;
UPDATE activity SET area = ('politico'), ente = ('00-00') WHERE id = 363;
UPDATE activity SET area = ('politico'), ente = ('00-00') WHERE id = 364;
UPDATE activity SET area = ('politico'), ente = ('00-00') WHERE id = 365;
UPDATE activity SET area = ('politico'), ente = ('00-00') WHERE id = 366;
UPDATE activity SET area = ('politico'), ente = ('00-00') WHERE id = 367;
UPDATE activity SET area = ('politico'), ente = ('00-00') WHERE id = 368;
UPDATE activity SET area = ('politico'), ente = ('00-00') WHERE id = 369;
UPDATE activity SET area = ('politico'), ente = ('00-00') WHERE id = 370;
UPDATE activity SET area = ('politico'), ente = ('00-00') WHERE id = 371;
UPDATE activity SET area = ('politico'), ente = ('00-00') WHERE id = 372;
UPDATE activity SET area = ('politico'), ente = ('00-00') WHERE id = 373;
UPDATE activity SET area = ('politico'), ente = ('00-00') WHERE id = 374;
UPDATE activity SET area = ('politico'), ente = ('00-00') WHERE id = 375;
UPDATE activity SET area = ('politico'), ente = ('00-00') WHERE id = 376;
UPDATE activity SET area = ('politico'), ente = ('00-00') WHERE id = 377;
UPDATE activity SET area = ('politico'), ente = ('00-00') WHERE id = 378;
UPDATE activity SET area = ('politico'), ente = ('00-00') WHERE id = 379;
UPDATE activity SET area = ('politico'), ente = ('00-00') WHERE id = 380;
UPDATE activity SET area = ('politico'), ente = ('00-00') WHERE id = 381;
UPDATE activity SET area = ('politico'), ente = ('00-00') WHERE id = 382;
UPDATE activity SET area = ('politico'), ente = ('00-00') WHERE id = 383;
UPDATE activity SET area = ('politico'), ente = ('00-00') WHERE id = 384;
UPDATE activity SET area = ('politico'), ente = ('00-00') WHERE id = 385;
UPDATE activity SET area = ('politico'), ente = ('00-00') WHERE id = 386;
UPDATE activity SET area = ('politico'), ente = ('00-00') WHERE id = 387;
UPDATE activity SET area = ('politico'), ente = ('00-00') WHERE id = 388;
UPDATE activity SET area = ('politico'), ente = ('00-00') WHERE id = 389;
UPDATE activity SET area = ('politico'), ente = ('00-00') WHERE id = 390;
UPDATE activity SET area = ('politico'), ente = ('00-00') WHERE id = 391;
UPDATE activity SET area = ('politico'), ente = ('00-00') WHERE id = 392;